Path to ServerAccessBeans
IBM/spm-ui-upgrade-helper pull request #198
Opened 2022-01-19 13:40 UTC by luizas

Update the Upgradehelper tool to point to the SERVER_DIR env variable to expected EJBServer directory

https://zenhub.ibm.com/app/workspaces/cobra-kai-5f62266cd7832b79d0be9e43/issues/wh-govspm/spm-components/3218

2022-01-20 12:12 UTC, bdjos1 reviewed
Greta job Luiza. The INPUT_FOLDER as noted in the documentation is essentially tjhe lcoation of the customer installation e.g https://ibm.github.io/spm-ui-upgrade-helper/run/running_the_tool, so the EJBServer directory will be already here.

The only thing I would say is we should be more specific with our error message if we detect that the 'EJBServer/build' directory does not exist as that means they have not built the server or at the very leaaast the model. So in the spm-ui-upgrade-helper.sh and spm-ui-upgrade-helper.bat file we should give a  specific message to that effect. Perhaps something like - You need to build the server or at the very least build the model e.g serverbuild.model

2022-01-20 22:04 UTC, bdjos1 approved these changes

2022-01-20 22:07 UTC, bdjos1 commented
Looks good to me Luiza. @poraghal Juts looking for a review if the error message in the spm-ui-upgradehelper.bat or spm-ui-upgradehelper.sh

2022-01-21 08:51 UTC, poraghal requested changes
Hi Luiza, it might be better if we leave in the cause of the error as well. Should Windows be backslash and Linux forward slash in code and message?

.bat

The ServerAccessBean path is missing. Build the server or the model to generate EJBserver\build, e.g. serverbuild.model

.sh

The ServerAccessBean path is missing. Build the server or the model to generate EJBserver/build, e.g. serverbuild.model

2022-01-21 09:49 UTC, poraghal approved these changes

2022-01-21 09:51 UTC, merged